name: socket_tunnel
description: A sample command-line application.
version: 1.0.4
repository: https://github.com/DesKaOne/socket_tunnel
publish_to: none

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  ansicolor: ^2.0.3
  archive: ^4.0.7
  convert: ^3.1.2
  crypto: ^3.0.6
  eventify: ^1.0.1
  http: ^1.5.0
  http_client:
    git: https://github.com/DesKaOne/http_client
  intl: ^0.20.2
  js: ^0.7.2
  logging: ^1.3.0
  path: ^1.9.1
  petitparser: ^7.0.1
  pointycastle: ^4.0.0
  socket_client:
    git: https://github.com/DesKaOne/socket_client
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
